name: Emoji Check

on: push

jobs:
  emoji-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify commit messages
        run: |
          # Récupérer les messages de commit
          commits=$(git log HEAD --pretty=format:"%s")

          # Vérifier si des commits ont été trouvés
          if [ -z "$commits" ]; then
              echo "❌ Aucun message de commit trouvé dans la plage spécifiée."
              exit 1
          fi

          # Vérifier la présence d'emoji dans chaque message de commit
          echo "$commits" | while read -r commit; do
              if ! echo "$commit" | grep -qP "[\x{1F600}-\x{1F64F}\x{1F300}-\x{1F5FF}\x{1F680}-\x{1F6FF}\x{2600}-\x{26FF}]"; then
                  echo "❌ Le message de commit suivant n'a pas d'emoji : $commit"
                  exit 1
              fi
          done

          echo "✅ Tous les commits contiennent des emojis."
